// ============================================================
//  TELUGU / ENGLISH LANGUAGE SYSTEM
//  Usage: t('key') returns translated string
// ============================================================
const TRANSLATIONS = {
  // NAV
  home:         { en: "Home",         te: "హోమ్" },
  meetings:     { en: "Meetings",     te: "సమావేశాలు" },
  complaints:   { en: "Complaints",   te: "ఫిర్యాదులు" },
  businesses:   { en: "Businesses",   te: "వ్యాపారాలు" },
  schemes:      { en: "Schemes",      te: "పథకాలు" },
  budget:       { en: "Budget",       te: "బడ్జెట్" },
  festivals:    { en: "Festivals",    te: "పండుగలు" },
  education:    { en: "Education",    te: "విద్య" },
  tourism:      { en: "Tourism",      te: "పర్యాటకం" },
  admin:        { en: "Admin",        te: "నిర్వహణ" },
  login:        { en: "Login",        te: "లాగిన్" },
  logout:       { en: "Sign out",     te: "నిష్క్రమించు" },

  // COMMON
  save:         { en: "Save",         te: "సేవ్ చేయి" },
  cancel:       { en: "Cancel",       te: "రద్దు చేయి" },
  delete:       { en: "Delete",       te: "తొలగించు" },
  edit:         { en: "Edit",         te: "మార్చు" },
  add:          { en: "Add",          te: "జోడించు" },
  submit:       { en: "Submit",       te: "సమర్పించు" },
  search:       { en: "Search",       te: "శోధించు" },
  loading:      { en: "Loading...",   te: "లోడవుతోంది..." },
  nodata:       { en: "No data found",te: "డేటా కనుగొనబడలేదు" },
  all:          { en: "All",          te: "అన్నీ" },
  upcoming:     { en: "Upcoming",     te: "రానున్న" },
  status:       { en: "Status",       te: "స్థితి" },
  name:         { en: "Name",         te: "పేరు" },
  phone:        { en: "Phone",        te: "ఫోన్" },
  date:         { en: "Date",         te: "తేదీ" },
  amount:       { en: "Amount",       te: "మొత్తం" },
  description:  { en: "Description",  te: "వివరణ" },
  location:     { en: "Location",     te: "స్థానం" },
  type:         { en: "Type",         te: "రకం" },
  category:     { en: "Category",     te: "వర్గం" },
  view_all:     { en: "View all →",   te: "అన్నీ చూడు →" },
  close:        { en: "Close",        te: "మూసివేయి" },
  open:         { en: "Open",         te: "తెరవు" },
  yes:          { en: "Yes",          te: "అవును" },
  no:           { en: "No",           te: "లేదు" },
  optional:     { en: "Optional",     te: "ఐచ్ఛికం" },
  required:     { en: "Required",     te: "తప్పనిసరి" },

  // HOME
  village_name:       { en: "Venkataraidupeta Village",     te: "వెంకటరాయుడుపేట గ్రామం" },
  village_sub:        { en: "Parvathipuram Mandal · Parvathipuram Manyam · Andhra Pradesh · PIN 535522", te: "పార్వతీపురం మండలం · పార్వతీపురం మన్యం · ఆంధ్రప్రదేశ్ · పిన్ 535522" },
  quote_telugu:       { en: '"My wish is that the people of our village be responsible, transparent and united."', te: '"మన గ్రామ ప్రజలు బాధ్యతగా, పారదర్శకంగా మరియు ఐకమత్యంగా ఉండాలని నా కోరిక."' },
  quick_access:       { en: "Quick Access",             te: "త్వరిత యాక్సెస్" },
  village_officials:  { en: "Village Officials",        te: "గ్రామ అధికారులు" },
  upcoming_meetings:  { en: "Upcoming Meetings",        te: "రానున్న సమావేశాలు" },
  faq:                { en: "Frequently Asked Questions", te: "తరచుగా అడిగే ప్రశ్నలు" },
  in_office:          { en: "In Office",                te: "పదవిలో" },
  president:          { en: "President (Sarpanch)",     te: "సర్పంచ్" },
  vro:                { en: "Village Revenue Officer",  te: "గ్రామ రెవెన్యూ అధికారి" },

  // STATS
  open_complaints:    { en: "Open Complaints",    te: "పెండింగ్ ఫిర్యాదులు" },
  village_businesses: { en: "Village Businesses", te: "గ్రామ వ్యాపారాలు" },
  govt_schemes:       { en: "Govt Schemes",       te: "ప్రభుత్వ పథకాలు" },
  upcoming_festivals: { en: "Upcoming Festivals", te: "రానున్న పండుగలు" },

  // MEETINGS
  add_meeting:        { en: "＋ Add Meeting",     te: "＋ సమావేశం జోడించు" },
  meeting_title:      { en: "Meeting Title",      te: "సమావేశం పేరు" },
  meeting_date:       { en: "Date & Time",        te: "తేదీ & సమయం" },
  organizer:          { en: "Organizer",          te: "నిర్వాహకుడు" },
  agenda:             { en: "Agenda",             te: "అజెండా" },
  minutes:            { en: "Minutes",            te: "నిమిషాలు" },
  add_minutes:        { en: "Add Minutes",        te: "నిమిషాలు జోడించు" },
  meeting_minutes:    { en: "Meeting Minutes",    te: "సమావేశ నిమిషాలు" },
  no_meetings:        { en: "No meetings found",  te: "సమావేశాలు కనుగొనబడలేదు" },

  // COMPLAINTS
  submit_complaint:   { en: "＋ Submit Complaint",    te: "＋ ఫిర్యాదు సమర్పించు" },
  your_name:          { en: "Your Name",              te: "మీ పేరు" },
  subject:            { en: "Subject",                te: "విషయం" },
  complaint_cat:      { en: "Category",               te: "వర్గం" },
  photo_optional:     { en: "Photo (Optional)",       te: "ఫోటో (ఐచ్ఛికం)" },
  upload_photo:       { en: "Click to upload photo",  te: "ఫోటో అప్లోడ్ చేయడానికి క్లిక్ చేయండి" },
  update_status:      { en: "Update Status",          te: "స్థితి నవీకరించు" },
  resolution_note:    { en: "Resolution Note",        te: "పరిష్కార గమనిక" },
  pending:            { en: "Pending",                te: "పెండింగ్" },
  in_progress:        { en: "In Progress",            te: "పురోగతిలో" },
  resolved:           { en: "Resolved",               te: "పరిష్కరించబడింది" },
  rejected:           { en: "Rejected",               te: "తిరస్కరించబడింది" },
  roads:              { en: "Roads",                  te: "రోడ్లు" },
  water_supply:       { en: "Water Supply",           te: "నీటి సరఫరా" },
  electricity:        { en: "Electricity",            te: "విద్యుత్" },
  sanitation:         { en: "Sanitation",             te: "పారిశుధ్యం" },
  drainage:           { en: "Drainage",               te: "మురుగు" },
  street_lights:      { en: "Street Lights",          te: "వీధి దీపాలు" },
  land_dispute:       { en: "Land Dispute",           te: "భూ వివాదం" },
  other:              { en: "Other",                  te: "ఇతర" },
  no_complaints:      { en: "No complaints found",   te: "ఫిర్యాదులు కనుగొనబడలేదు" },
  resolution:         { en: "Resolution",             te: "పరిష్కారం" },
  submitted:          { en: "Submitted",              te: "సమర్పించబడింది" },

  // BUSINESSES
  add_shop:           { en: "＋ Add Shop",         te: "＋ దుకాణం జోడించు" },
  shop_name:          { en: "Shop Name",           te: "దుకాణం పేరు" },
  owner_name:         { en: "Owner Name",          te: "యజమాని పేరు" },
  address:            { en: "Address",             te: "చిరునామా" },
  opens_at:           { en: "Opens At",            te: "తెరిచే సమయం" },
  closes_at:          { en: "Closes At",           te: "మూసే సమయం" },
  products:           { en: "Products",            te: "ఉత్పత్తులు" },
  search_products:    { en: "Search Products",     te: "ఉత్పత్తులు శోధించు" },
  add_product:        { en: "＋ Add Product",      te: "＋ ఉత్పత్తి జోడించు" },
  price:              { en: "Price (₹)",           te: "ధర (₹)" },
  unit:               { en: "Unit",                te: "యూనిట్" },
  available:          { en: "Available",           te: "అందుబాటులో" },
  in_stock:           { en: "In Stock",            te: "స్టాక్ లో ఉంది" },
  out_of_stock:       { en: "Out of Stock",        te: "స్టాక్ లేదు" },
  closed:             { en: "Closed",              te: "మూసివేయబడింది" },
  no_businesses:      { en: "No businesses found", te: "వ్యాపారాలు కనుగొనబడలేదు" },
  search_by_name:     { en: "Search by shop or owner name...", te: "దుకాణం లేదా యజమాని పేరు వెతకండి..." },
  all_categories:     { en: "All Categories",      te: "అన్ని వర్గాలు" },

  // SCHEMES
  eligibility_checker:{ en: "Eligibility Checker", te: "అర్హత పరీక్షకం" },
  check_eligibility:  { en: "Check My Eligibility",te: "నా అర్హత తనిఖీ చేయి" },
  gender:             { en: "Gender",              te: "లింగం" },
  male:               { en: "Male",                te: "పురుషుడు" },
  female:             { en: "Female",              te: "స్త్రీ" },
  age:                { en: "Age",                 te: "వయసు" },
  income_category:    { en: "Income Category",     te: "ఆదాయ వర్గం" },
  bpl:                { en: "BPL (Below Poverty Line)", te: "బిపిఎల్ (దారిద్ర్య రేఖకు దిగువన)" },
  low_income:         { en: "Low Income",          te: "తక్కువ ఆదాయం" },
  middle_income:      { en: "Middle Income",       te: "మధ్యతరగతి ఆదాయం" },
  higher_income:      { en: "Higher Income",       te: "అధిక ఆదాయం" },
  are_you_farmer:     { en: "Are you a Farmer?",   te: "మీరు రైతు అయినారా?" },
  own_land:           { en: "Do you own land?",    te: "మీకు భూమి ఉందా?" },
  caste_category:     { en: "Caste Category",      te: "కులం వర్గం" },
  general:            { en: "General / OC",        te: "జనరల్ / ఓసి" },
  sc_st:              { en: "SC / ST",             te: "ఎస్సీ / ఎస్టీ" },
  bc:                 { en: "BC",                  te: "బిసి" },
  you_qualify:        { en: "You qualify for",     te: "మీరు అర్హులు" },
  schemes_label:      { en: "scheme(s)!",          te: "పథకాలకు!" },
  apply_online:       { en: "Apply Online ↗",      te: "ఆన్లైన్లో దరఖాస్తు చేయండి ↗" },
  benefits:           { en: "Benefits",            te: "ప్రయోజనాలు" },
  documents:          { en: "Documents Required",  te: "అవసరమైన పత్రాలు" },
  farmers:            { en: "Farmers",             te: "రైతులు" },
  women:              { en: "Women",               te: "మహిళలు" },
  health:             { en: "Health",              te: "ఆరోగ్యం" },
  housing:            { en: "Housing",             te: "గృహనిర్మాణం" },
  employment:         { en: "Employment",          te: "ఉపాధి" },
  senior:             { en: "Senior Citizen",      te: "వృద్ధులు" },
  no_schemes:         { en: "No schemes matched",  te: "పథకాలు సరిపోలలేదు" },

  // BUDGET
  budget_title:       { en: "Panchayat Budget Transparency", te: "పంచాయతీ బడ్జెట్ పారదర్శకత" },
  total_allocated:    { en: "Total Allocated",     te: "మొత్తం కేటాయించిన" },
  total_spent:        { en: "Total Spent",         te: "మొత్తం ఖర్చు" },
  remaining:          { en: "Remaining",           te: "మిగిలింది" },
  total_projects:     { en: "Total Projects",      te: "మొత్తం ప్రాజెక్టులు" },
  completed:          { en: "Completed",           te: "పూర్తయింది" },
  planned:            { en: "Planned",             te: "ప్రణాళిక చేయబడింది" },
  on_hold:            { en: "On Hold",             te: "నిలిపివేయబడింది" },
  add_project:        { en: "＋ Add Project",      te: "＋ ప్రాజెక్ట్ జోడించు" },
  project_name:       { en: "Project Name",        te: "ప్రాజెక్ట్ పేరు" },
  financial_year:     { en: "Financial Year",      te: "ఆర్థిక సంవత్సరం" },
  fund_source:        { en: "Fund Source",         te: "నిధి మూలం" },
  remarks:            { en: "Remarks",             te: "వ్యాఖ్యలు" },
  utilised:           { en: "utilised",            te: "వినియోగించబడింది" },
  all_projects:       { en: "All Projects",        te: "అన్ని ప్రాజెక్టులు" },
  allocated:          { en: "Allocated",           te: "కేటాయించిన" },
  spent:              { en: "Spent",               te: "ఖర్చు" },
  budget_util:        { en: "Overall Budget Utilization", te: "మొత్తం బడ్జెట్ వినియోగం" },

  // FESTIVALS
  add_festival:       { en: "＋ Add Festival",     te: "＋ పండుగ జోడించు" },
  festival_name:      { en: "Festival Name",       te: "పండుగ పేరు" },
  committee:          { en: "Organizer / Committee",te: "నిర్వాహకులు / కమిటీ" },
  finance_events:     { en: "Finance & Events",    te: "ఆర్థికం & కార్యక్రమాలు" },
  fund_collections:   { en: "Fund Collections",    te: "నిధి సేకరణ" },
  expenses:           { en: "Expenses",            te: "ఖర్చులు" },
  events:             { en: "Events",              te: "కార్యక్రమాలు" },
  total_collected:    { en: "Total Collected",     te: "మొత్తం సేకరించిన" },
  total_expense:      { en: "Total Spent",         te: "మొత్తం ఖర్చు" },
  balance:            { en: "Balance Remaining",   te: "మిగిలిన నిల్వ" },
  over_budget:        { en: "Over Budget",         te: "బడ్జెట్ మించింది" },
  donor:              { en: "Donor / Villager Name",te: "దాత / గ్రామస్తుడు పేరు" },
  collected_by:       { en: "Collected By",        te: "సేకరించిన వ్యక్తి" },
  add_collection:     { en: "＋ Add Collection",   te: "＋ సేకరణ జోడించు" },
  add_expense:        { en: "＋ Add Expense",      te: "＋ ఖర్చు జోడించు" },
  add_event:          { en: "＋ Add Event",         te: "＋ కార్యక్రమం జోడించు" },
  expense_item:       { en: "Expense Item",        te: "ఖర్చు వివరాలు" },
  paid_to:            { en: "Paid To / Vendor",    te: "చెల్లించిన వ్యక్తి / విక్రేత" },
  event_name:         { en: "Event Name",          te: "కార్యక్రమం పేరు" },
  venue:              { en: "Venue",               te: "వేదిక" },
  prize:              { en: "Prize / Reward",      te: "బహుమతి" },
  incharge:           { en: "Organizer / In-charge",te: "నిర్వాహకుడు" },
  no_festivals:       { en: "No festivals found",  te: "పండుగలు కనుగొనబడలేదు" },

  // EDUCATION
  add_entry:          { en: "＋ Add Entry",        te: "＋ నమోదు జోడించు" },
  scholarships:       { en: "Scholarships",        te: "స్కాలర్షిప్లు" },
  schools:            { en: "Schools",             te: "పాఠశాలలు" },
  results:            { en: "Results",             te: "ఫలితాలు" },
  coaching:           { en: "Coaching",            te: "కోచింగ్" },
  awareness:          { en: "Awareness",           te: "అవగాహన" },
  institution:        { en: "Institution",         te: "సంస్థ" },
  contact_person:     { en: "Contact Person",      te: "సంప్రదింపు వ్యక్తి" },
  last_date:          { en: "Last Date",           te: "చివరి తేదీ" },
  eligibility:        { en: "Eligibility",         te: "అర్హత" },
  app_link:           { en: "Application Link",    te: "దరఖాస్తు లింక్" },
  no_education:       { en: "No entries found",   te: "నమోదులు కనుగొనబడలేదు" },

  // TOURISM
  add_spot:           { en: "＋ Add Spot",         te: "＋ స్థలం జోడించు" },
  spot_name:          { en: "Spot Name",           te: "స్థలం పేరు" },
  best_time:          { en: "Best Time to Visit",  te: "సందర్శించడానికి మంచి సమయం" },
  entry_fee:          { en: "Entry Fee",           te: "ప్రవేశ రుసుము" },
  nearest_landmark:   { en: "Nearest Landmark",    te: "సమీప ల్యాండ్‌మార్క్" },
  no_spots:           { en: "No tourist spots found", te: "పర్యాటక స్థలాలు కనుగొనబడలేదు" },

  // LOGIN
  welcome_back:       { en: "Welcome back",        te: "తిరిగి స్వాగతం" },
  sign_in:            { en: "Sign In →",           te: "లాగిన్ చేయి →" },
  username:           { en: "Username",            te: "వినియోగదారు పేరు" },
  password:           { en: "Password",            te: "పాస్‌వర్డ్" },
  view_portal:        { en: "View public portal →", te: "పబ్లిక్ పోర్టల్ చూడు →" },

  // ADMIN
  admin_dash:         { en: "Admin Dashboard",     te: "నిర్వహణ డాష్‌బోర్డు" },
  quick_actions:      { en: "Quick Actions",       te: "త్వరిత చర్యలు" },
  register_user:      { en: "Register New User",   te: "కొత్త వినియోగదారుని నమోదు చేయి" },
  full_name:          { en: "Full Name",           te: "పూర్తి పేరు" },
  role:               { en: "Role",                te: "పాత్ర" },
  register_btn:       { en: "Register User",       te: "వినియోగదారుని నమోదు చేయి" },
  pending_complaints: { en: "Pending Complaints",  te: "పెండింగ్ ఫిర్యాదులు" },
};

function getLang() { return localStorage.getItem("svp_lang") || "en"; }
function setLang(l) { localStorage.setItem("svp_lang", l); location.reload(); }
function t(key) {
  const lang = getLang();
  return TRANSLATIONS[key] ? (TRANSLATIONS[key][lang] || TRANSLATIONS[key]["en"]) : key;
}
function toggleLang() { setLang(getLang() === "en" ? "te" : "en"); }

// Apply lang attribute for font support
document.documentElement.lang = getLang();
